services:
  todo:
    image: todo
    build:
      context: ./todo
      dockerfile: Dockerfile
    container_name: todo
    networks:
      - todo_network
    expose:
      - "8000"
    restart: unless-stopped
    init: true

  nginx:
    image: nginx
    depends_on:
          - todo
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - todo_network
    ports:
      - "5000:5000"
      - "5355:5355"
    volumes:
      - ./nginx/js_app:/var/www/html
    restart: unless-stopped
    init: true

networks:
  todo_network:
    name: todo_network
    driver: bridge

